[package]
name = "sfml-build"
version = "0.1.0"
authors = ["rust-sfml developers"]
description = "Common routines for finding and linking native (C)SFML libraries"
license = "zlib-acknowledgement"
keywords = ["sfml", "multimedia", "game"]
