name: Build and test (Mac OS)

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'examples/**'
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '.github/workflows/macos.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'examples/**'
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '.github/workflows/macos.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: 1.82.0
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        brew install freetype libvorbis
    - name: Build
      run: |
       git submodule update --init
       cargo build --verbose
    - name: Run tests
      run: |
       cargo test --features ci-headless --verbose
       # Release can have different build configuration, so test it
       cargo test --release --features=ci-headless --verbose
       # Also test non-default feature combinations
       cargo test --no-default-features --features=ci-headless --verbose
       cargo test --no-default-features --features=ci-headless,audio --verbose
       cargo test --no-default-features --features=ci-headless,window --verbose
       cargo test --no-default-features --features=ci-headless,graphics --verbose
    - name: TMate debug tests
      if: ${{ failure() }}
      uses: mxschmitt/action-tmate@v3